In [1]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("C:\\Users\\guilh_000\\Documents\\Titanic-Competition\\train.csv")
test = pd.read_csv("C:\\Users\\guilh_000\\Documents\\Titanic-Competition\\test.csv")

In [3]:
train.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [7]:
train.drop(['Name', 'Cabin'], axis=1, inplace=True)
train.head(20)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0             1         0       3    male  22.0      1      0   
1             2         1       1  female  38.0      1      0   
2             3         1       3  female  26.0      0      0   
3             4         1       1  female  35.0      1      0   
4             5         0       3    male  35.0      0      0   
5             6         0       3    male   NaN      0      0   
6             7         0       1    male  54.0      0      0   
7             8         0       3    male   2.0      3      1   
8             9         1       3  female  27.0      0      2   
9            10         1       2  female  14.0      1      0   
10           11         1       3  female   4.0      1      1   
11           12         1       1  female  58.0      0      0   
12           13         0       3    male  20.0      0      0   
13           14         0       3    male  39.0      1      5   
14           15         0       3  female  14.0      0      0   
15           16         1       2  female  55.0      0      0   
16           17         0       3    male   2.0      4      1   
17           18         1       2    male   NaN      0      0   
18           19         0       3  female  31.0      1      0   
19           20         1       3  female   NaN      0      0   

              Ticket     Fare Embarked  
0          A/5 21171   7.2500        S  
1           PC 17599  71.2833        C  
2   STON/O2. 3101282   7.9250        S  
3             113803  53.1000        S  
4             373450   8.0500        S  
5             330877   8.4583        Q  
6              17463  51.8625        S  
7             349909  21.0750        S  
8             347742  11.1333        S  
9             237736  30.0708        C  
10           PP 9549  16.7000        S  
11            113783  26.5500        S  
12         A/5. 2151   8.0500        S  
13            347082  31.2750        S  
14            350406   7.8542        S  
15            248706  16.0000        S  
16            382652  29.1250        Q  
17            244373  13.0000        S  
18            345763  18.0000        S  
19              2649   7.2250        C

In [8]:
train.drop(['Ticket'], axis=1, inplace=True)
train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [9]:
train['Age'].mean()

#fill NaN values with mean value

29.69911764705882

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [11]:
train['Age'] = train['Age'].fillna(train['Age'].mean())
train.head(20)

PassengerId  Survived  Pclass     Sex        Age  SibSp  Parch     Fare  \
0             1         0       3    male  22.000000      1      0   7.2500   
1             2         1       1  female  38.000000      1      0  71.2833   
2             3         1       3  female  26.000000      0      0   7.9250   
3             4         1       1  female  35.000000      1      0  53.1000   
4             5         0       3    male  35.000000      0      0   8.0500   
5             6         0       3    male  29.699118      0      0   8.4583   
6             7         0       1    male  54.000000      0      0  51.8625   
7             8         0       3    male   2.000000      3      1  21.0750   
8             9         1       3  female  27.000000      0      2  11.1333   
9            10         1       2  female  14.000000      1      0  30.0708   
10           11         1       3  female   4.000000      1      1  16.7000   
11           12         1       1  female  58.000000      0      0  26.5500   
12           13         0       3    male  20.000000      0      0   8.0500   
13           14         0       3    male  39.000000      1      5  31.2750   
14           15         0       3  female  14.000000      0      0   7.8542   
15           16         1       2  female  55.000000      0      0  16.0000   
16           17         0       3    male   2.000000      4      1  29.1250   
17           18         1       2    male  29.699118      0      0  13.0000   
18           19         0       3  female  31.000000      1      0  18.0000   
19           20         1       3  female  29.699118      0      0   7.2250   

   Embarked  
0         S  
1         C  
2         S  
3         S  
4         S  
5         Q  
6         S  
7         S  
8         S  
9         C  
10        S  
11        S  
12        S  
13        S  
14        S  
15        S  
16        Q  
17        S  
18        S  
19        C

In [12]:
train['Embarked'] = train['Embarked'].fillna('S')
train.info()

#fill NanN values with most frequent value 'S'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [14]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(train[col]))

In [15]:
titanic_dummies = pd.concat(dummies, axis=1)

In [16]:
titanic_dummies.head()

1  2  3  female  male  C  Q  S
0  0  0  1       0     1  0  0  1
1  1  0  0       1     0  1  0  0
2  0  0  1       1     0  0  0  1
3  1  0  0       1     0  0  0  1
4  0  0  1       0     1  0  0  1

In [17]:
train = pd.concat((train,titanic_dummies), axis=1)
train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   

  Embarked  1  2  3  female  male  C  Q  S  
0        S  0  0  1       0     1  0  0  1  
1        C  1  0  0       1     0  1  0  0  
2        S  0  0  1       1     0  0  0  1  
3        S  1  0  0       1     0  0  0  1  
4        S  0  0  1       0     1  0  0  1

In [18]:
train = train.drop(['Pclass', 'Sex', 'Embarked'], axis=1)
train.head()

PassengerId  Survived   Age  SibSp  Parch     Fare  1  2  3  female  male  \
0            1         0  22.0      1      0   7.2500  0  0  1       0     1   
1            2         1  38.0      1      0  71.2833  1  0  0       1     0   
2            3         1  26.0      0      0   7.9250  0  0  1       1     0   
3            4         1  35.0      1      0  53.1000  1  0  0       1     0   
4            5         0  35.0      0      0   8.0500  0  0  1       0     1   

   C  Q  S  
0  0  0  1  
1  1  0  0  
2  0  0  1  
3  0  0  1  
4  0  0  1

In [19]:
train.columns

Index(['PassengerId',    'Survived',         'Age',       'SibSp',
             'Parch',        'Fare',             1,             2,
                   3,      'female',        'male',           'C',
                 'Q',           'S'],
      dtype='object')

In [63]:
X = train[[ 'Age',       'SibSp',
             'Parch',        'Fare',             1,             2,
                   3,      'female',        'male',           'C',
                 'Q',           'S']]


In [64]:
y = train.iloc[:,1]

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [72]:
from sklearn import svm
clf = svm.SVC(C= 1, kernel='linear')
clf.fit(X_train, y_train)

SVC(C=1, kernel='linear')

In [71]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support, classification_report

y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[115  24]
 [ 25  59]]
              precision    recall  f1-score   support

           0       0.82      0.83      0.82       139
           1       0.71      0.70      0.71        84

    accuracy                           0.78       223
   macro avg       0.77      0.76      0.77       223
weighted avg       0.78      0.78      0.78       223

0.7802690582959642


In [ ]:
[[115  24]
 [ 25  59]]
              precision    recall  f1-score   support

           0       0.82      0.83      0.82       139
           1       0.71      0.70      0.71        84

    accuracy                           0.78       223
   macro avg       0.77      0.76      0.77       223
weighted avg       0.78      0.78      0.78       223

0.7802690582959642

In [43]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=0)
lrc.fit(X_train, y_train)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=0)

In [44]:
y_pred = lrc.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[116  23]
 [ 23  61]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       139
           1       0.73      0.73      0.73        84

    accuracy                           0.79       223
   macro avg       0.78      0.78      0.78       223
weighted avg       0.79      0.79      0.79       223

0.7937219730941704


In [47]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=5, random_state=0)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=0)

In [48]:
y_pred = rfc.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[122  17]
 [ 26  58]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       139
           1       0.77      0.69      0.73        84

    accuracy                           0.81       223
   macro avg       0.80      0.78      0.79       223
weighted avg       0.81      0.81      0.80       223

0.8071748878923767


In [49]:
###going with linear svm
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [50]:
test['Age'] = test['Age'].fillna(test['Age'].mean())
test['Fare'] = test['Fare'].fillna(test['Fare'].mean())
test.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           418 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [51]:
newtest = test[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'Embarked']]
newtest.head(20)

PassengerId  Pclass     Sex       Age  SibSp  Parch     Fare Embarked
0           892       3    male  34.50000      0      0   7.8292        Q
1           893       3  female  47.00000      1      0   7.0000        S
2           894       2    male  62.00000      0      0   9.6875        Q
3           895       3    male  27.00000      0      0   8.6625        S
4           896       3  female  22.00000      1      1  12.2875        S
5           897       3    male  14.00000      0      0   9.2250        S
6           898       3  female  30.00000      0      0   7.6292        Q
7           899       2    male  26.00000      1      1  29.0000        S
8           900       3  female  18.00000      0      0   7.2292        C
9           901       3    male  21.00000      2      0  24.1500        S
10          902       3    male  30.27259      0      0   7.8958        S
11          903       1    male  46.00000      0      0  26.0000        S
12          904       1  female  23.00000      1      0  82.2667        S
13          905       2    male  63.00000      1      0  26.0000        S
14          906       1  female  47.00000      1      0  61.1750        S
15          907       2  female  24.00000      1      0  27.7208        C
16          908       2    male  35.00000      0      0  12.3500        Q
17          909       3    male  21.00000      0      0   7.2250        C
18          910       3  female  27.00000      1      0   7.9250        S
19          911       3  female  45.00000      0      0   7.2250        C

In [53]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(newtest[col]))

In [54]:
titanic_dummies = pd.concat(dummies, axis=1)
titanic_dummies.head()

1  2  3  female  male  C  Q  S
0  0  0  1       0     1  0  1  0
1  0  0  1       1     0  0  0  1
2  0  1  0       0     1  0  1  0
3  0  0  1       0     1  0  0  1
4  0  0  1       1     0  0  0  1

In [55]:
newtest = pd.concat((newtest,titanic_dummies), axis=1)
newtest.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  1  2  3  \
0          892       3    male  34.5      0      0   7.8292        Q  0  0  1   
1          893       3  female  47.0      1      0   7.0000        S  0  0  1   
2          894       2    male  62.0      0      0   9.6875        Q  0  1  0   
3          895       3    male  27.0      0      0   8.6625        S  0  0  1   
4          896       3  female  22.0      1      1  12.2875        S  0  0  1   

   female  male  C  Q  S  
0       0     1  0  1  0  
1       1     0  0  0  1  
2       0     1  0  1  0  
3       0     1  0  0  1  
4       1     0  0  0  1

In [56]:
newtest = newtest.drop(['Pclass', 'Sex', 'Embarked'], axis=1)
newtest.head()

PassengerId   Age  SibSp  Parch     Fare  1  2  3  female  male  C  Q  S
0          892  34.5      0      0   7.8292  0  0  1       0     1  0  1  0
1          893  47.0      1      0   7.0000  0  0  1       1     0  0  0  1
2          894  62.0      0      0   9.6875  0  1  0       0     1  0  1  0
3          895  27.0      0      0   8.6625  0  0  1       0     1  0  0  1
4          896  22.0      1      1  12.2875  0  0  1       1     0  0  0  1

In [73]:
newtest = newtest.drop(['PassengerId'], axis=1)
newtest.head()

Age  SibSp  Parch     Fare  1  2  3  female  male  C  Q  S
0  34.5      0      0   7.8292  0  0  1       0     1  0  1  0
1  47.0      1      0   7.0000  0  0  1       1     0  0  0  1
2  62.0      0      0   9.6875  0  1  0       0     1  0  1  0
3  27.0      0      0   8.6625  0  0  1       0     1  0  0  1
4  22.0      1      1  12.2875  0  0  1       1     0  0  0  1

In [74]:
S = clf.predict(newtest)

In [75]:
S

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [76]:
test['Survived'] = S

In [77]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [78]:
data = test[['PassengerId', 'Survived']]
data.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [79]:
data.to_csv("C:\\Users\\guilh_000\\Documents\\Titanic-Competition\\datafourth.csv", index = False, header=True)